export default (ActionTypes = {
  ADD_VALUE: "ADD_VALUE",
  SUB_VALUE: "SUB_VALUE",
  RESET: "RESET",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAIL: "PAYMENT_FAIL",
  ADD_TO_CART: "ADD_TO_CART",
  HIDE_CART_BTN: "HIDE_CART_BTN",
  USER_PROFILE: "USER_PROFILE",
  EMPTY_CART_LIST: "EMPTY_CART_LIST",
  EXAMPLE_DATA: "EXAMPLE_DATA",
  LOG_OUT: "LOG_OUT",
  COPY: "COPY"
});
