export default (ActionTypes = {
  ADD_VALUE: "ADD_VALUE",
  SUB_VALUE: "SUB_VALUE",
  RESET: "RESET",
  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAIL: "PAYMENT_FAIL",
  ADD_TO_CART: "ADD_TO_CART",
  HIDE_CART_BTN: "HIDE_CART_BTN"
});
